name: playbucks
description: A new and innovative music promoting platform for music lovers and artistes.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash:
  flutter_screenutil:
  flutter_boxicons:
  flutter_spinkit:
  flutter_launcher_icons:
  flutter_riverpod:
  flutter_svg:
  go_router:
  dio:
  audioplayers:
  audio_waveforms_fix:
  file_picker:
  glassmorphism:
  path_provider:
  audio_service:
  intl:
  url_launcher:
  badges:
  equatable:
  flex_color_scheme:
  animated_switcher_plus:
  dropdown_button2:
  fluttertoast:
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  image_path_android: "images/logo.png"
  image_path_ios: "images/logo.png"
  android: true
  ios: true
  adaptive_icon_background: "#1E1E1E"
  adaptive_icon_foreground: "images/logo.png"
  min_sdk_android: 29
  remove_alpha_ios: true

flutter_native_splash:
  color: "#121113"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito-Italic.ttf
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-Medium.ttf
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf